### ISSUE TITLE
Factorial

### ISSUE THREAD

**Issue by dy** [evanw/theta#4]
Hi @evanw!
It is not possible to use common math factorial notation `x!` now.
Are there plans to introduce that?
Thanks.

**Comment by evanw** [comment]
The factorial notation [y = x!](http://thetamath.com/app/y=x!) should be working now. It's implemented as a continuous curve using the gamma function [y = Γ(x + 1)](http://thetamath.com/app/y=%CE%93%28x+1%29) instead of as a discrete function over the integers.

**Comment by dy** [comment]
@evanw thanks for that, I was looking for the function covering facrorial) Now I can try to plot poisson distribution density.
