### ISSUE TITLE
What's Smooth Shaders for?

### ISSUE THREAD

**Issue by orklann** [evanw/theta#6]
Hi,

In your [post](https://medium.com/@evanwallace/easy-scalable-text-rendering-on-the-gpu-c3f4d782c5ac#.r978lktr9), you did not mention anything on this [smooth shader](https://github.com/evanw/theta/blob/master/glslx/shaders.glslx#L18), can you make some simple explanation on this shader? I can not figure out why this shader can improve the smooth of the glyphs.

Thanks.

**Comment by evanw** [comment]
This is for drawing anti-aliased lines, which are used for decorations such as grid lines, brackets, and the square root symbol. It's not used for text rendering.
