### ISSUE TITLE
y = sin(x)^7 bug

### ISSUE THREAD

**Issue by dy** [evanw/theta#8]
Thetamath:

![image](https://cloud.githubusercontent.com/assets/300067/18415585/8568d918-77c5-11e6-8547-99ff56a52e2e.png)

Google and common sense:

![image](https://cloud.githubusercontent.com/assets/300067/18415589/a5785fee-77c5-11e6-8d92-aeea17f29fdb.png)

Something is wrong here

**Comment by KubaO** [comment]
For me, all odd powers 5 and above are similarly broken.

**Comment by evanw** [comment]
Just fixed this. It turns out `pow()` is wrong for odd powers on some graphics cards.
